export const galleryImages = [
  {
    id: 1,
    src: "src/assets/gallery/png1.png",
    alt: "Hello",
    description: "Productive workspace vibes",
  },
  {
    id: 2,
    src: "src/assets/gallery/png2.png",
    alt: "Hello",
    description: "Modern technology",
  },
  {
    id: 3,
    src: "src/assets/gallery/png3.png",
    alt: "Circuit board macro",
    description: "Digital circuits",
  },
  {
    id: 4,
    src: "src/assets/gallery/png4.png",
    alt: "Java programming monitor",
    description: "Code in action",
  },
  {
    id: 5,
    src: "src/assets/gallery/png4.png",
    alt: "Two deer in forest",
    description: "Wildlife photography",
  },
  {
    id: 6,
    src: "src/assets/gallery/png6.png",
    alt: "Bridge and waterfalls",
    description: "Natural wonder",
  },
  {
    id: 7,
    src: "src/assets/gallery/png7.png",
    alt: "Orange flowers",
    description: "Vibrant blooms",
  },
  {
    id: 8,
    src: "src/assets/gallery/png6.png",
    alt: "Ocean wave",
    description: "Ocean power",
  },
  {
    id: 9,
    src: "src/assets/gallery/png1.png",
    alt: "Modern building",
    description: "Urban architecture",
  },
  {
    id: 10,
    src: "src/assets/gallery/png2.png",
    alt: "Glass building",
    description: "Geometric design",
  },
  {
    id: 11,
    src: "src/assets/gallery/png3.png",
    alt: "Grey tabby kitten",
    description: "Adorable feline",
  },
  {
    id: 12,
    src: "src/assets/gallery/png4.png",
    alt: "Humpback whale jumping",
    description: "Marine magnificence",
  },
  {
    id: 13,
    src: "src/assets/gallery/png5.png",
    alt: "Lake surrounded by trees",
    description: "Serene landscape",
  },
  {
    id: 14,
    src: "src/assets/gallery/png6.png",
    alt: "Two deer in woods",
    description: "Forest dwellers",
  },
  {
    id: 15,
    src: "src/assets/gallery/png7.png",
    alt: "Glass building bottom view",
    description: "Looking up",
  },
  {
    id: 16,
    src: "src/assets/gallery/png1.png",
    alt: "Glass building",
    description: "Geometric design",
  },
  {
    id: 17,
    src: "src/assets/gallery/png3.png",
    alt: "Grey tabby kitten",
    description: "Adorable feline",
  },
  {
    id: 18,
    src: "src/assets/gallery/png4.png",
    alt: "Humpback whale jumping",
    description: "Marine magnificence",
  },
  {
    id: 19,
    src: "src/assets/gallery/png5.png",
    alt: "Lake surrounded by trees",
    description: "Serene landscape",
  },
];
